### PR TITLE
Fix : Issue Printing Virtual Hosts

### PR DESCRIPTION
**Pull request by maximebeck**
When creating multiple virtual hosts in Apache httpd, BMX would not display all of them.

### CODE REVIEW

**Comment by jfclere** [comment]
The patch doesn't look quite right to me... it seems to change server_rec which is wrong.

**Comment by wrowe** [comment]
There is a simpler solution, and given the formatting issues/typos I can't commit this as a merge, but will split this into the original two purposes and offer two cleaner fixes for the bug and compilation issues maximebeck has identified.  Thanks for the submission!

**Comment by wrowe** [comment]
jfclere has cleaned up the top-server patch you had proposed maximebeck, so the second half of your proposal - to catch missing vhosts - is now in trunk.

**Comment by wrowe** [comment]
Port differentiation is now in place, I believe each aspect addressed by the proposed patch is now incorporated. Again, thank you for the submission!

**Pull request merged**
